validator: clean-validator
	g++ -o validator validator.cpp --std=c++17

clean-validator:
	rm -f validator


#-----------------------------------------------

graph-gen: clean-graph-gen
	g++ -o graph-gen graph-gen.cpp --std=c++17

clean-graph-gen:
	rm -f graph-gen